WebsiteMVC/Models/House.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public House()
        {
            this.AddressHouses = new HashSet<AddressHouse>();
            this.ImageHouses = new HashSet<ImageHouse>();
            this.InfoHouses = new HashSet<InfoHouse>();
        }
    
        public int IDHouse { get; set; }
        public string Code { get; set; }
        public Nullable<int> IDTaiKhoan { get; set; }
        public string Name { get; set; }
        public string Sumary { get; set; }
        public Nullable<int> IDDuAn { get; set; }
        public Nullable<int> Views { get; set; }
        public string Type { get; set; }
        public string IDMap { get; set; }
        public Nullable<int> BedRoom { get; set; }
        public Nullable<int> Area { get; set; }
        public string Price { get; set; }
        public Nullable<byte> State { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddressHouse> AddressHouses { get; set; }
        public virtual DuAn DuAn { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageHouse> ImageHouses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InfoHouse> InfoHouses { get; set; }
    }
}

WebsiteMVC/Models/InfoHouse.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoHouse
    {
        public int IDInfoHouse { get; set; }
        public Nullable<int> IDHouse { get; set; }
        public Nullable<int> IDKey { get; set; }
        public string Value { get; set; }
    
        public virtual House House { get; set; }
        public virtual Key Key { get; set; }
    }
}

WebsiteMVC/Areas/AdminCP/Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteMVC.Models;

namespace WebsiteMVC.Areas.AdminCP.Controllers
{
    public class HouseController : AdminController
    {
        public ActionResult Index()
        {
            return View(db.Houses.Where(q => q.State != MState.DELETE));
        }

        public JsonResult Delete(int id)
        {
            var ob = db.Houses.Find(id);
            ob.State = MState.DELETE;
            return Json(db.SaveChanges());
        }

        public ActionResult Edit(int? id)
        {
            House obj = new House();
            if (id > 0)
            {
                obj = db.Houses.Find(id);
            }
            ViewBag.IDTaiKhoans = db.TaiKhoans.Where(q => q.State != MState.DELETE).CreateSelectList(q => q.IDTaiKhoan, q => q.FullName, obj?.IDTaiKhoan);
            ViewBag.IDDuAns = db.DuAns.Where(q => q.State != MState.DELETE).CreateSelectList(q => q.IDDuAn, q => q.Name, obj?.IDDuAn);

            _fillInfo(db.Houses.Find(id));
            ViewBag.xAddress1s = db.Addresses.Where(q => q.Rank == 1).CreateSelectList(q => q.IDAddress, q => q.Name, obj?.xAddress1?.IDAddress);
            ViewBag.xAddress2s = db.Addresses.Where(q => q.Rank == 2).CreateSelectList(q => q.IDAddress, q => q.Name, obj?.xAddress2?.IDAddress);
            ViewBag.xAddress3s = db.Addresses.Where(q => q.Rank == 3).CreateSelectList(q => q.IDAddress, q => q.Name, obj?.xAddress3?.IDAddress);

            return View(obj);
        }

        public ActionResult InfoHouse(int? id)
        {
            var lst = new List<InfoHouse>();
            var ob = db.Houses.Find(id);
            var allKeys = db.Keys.Where(q => q.Category.State.Contains("house") && q.Active != false).ToList();
            if (id > 0)
            {
                allKeys.ForEach(item =>
                {
                    var obj = ob.InfoHouses.FirstOrDefault(q => q.IDKey == item.IDKey);
                    if (obj == null)
                    {
                        lst.Add(new Models.InfoHouse
                        {
                            House = new House { },
                            IDHouse = 0,
                            IDInfoHouse = 0,
                            IDKey = item.IDKey,
                            Key = item,
                            Value = ""
                        });
                    }
                    else
                    {
                        lst.Add(obj);
                    }
                });
            }
            else
            {
                allKeys.ForEach(a =>
                {
                    lst.Add(new Models.InfoHouse
                    {
                        House = new House { },
                        IDHouse = 0,
                        IDInfoHouse = 0,
                        IDKey = a.IDKey,
                        Key = a,
                        Value = ""
                    });
                });
            }
            return View(lst);
        }

        [HttpPost]
        public ActionResult Edit(House obj, InfoHouse[] InfoHouse, int IDAddress1, int IDAddress2, int IDAddress3, HttpPostedFileBase[] Image)
        {
            if (obj.IDHouse == 0)
            {
                db.Houses.Add(obj);
                db.SaveChanges();

                InfoHouse.ToList().ForEach(q =>
                {
                    q.IDHouse = obj.IDHouse;
                    db.InfoHouses.Add(q);
                });
                db.AddressHouses.Add(new AddressHouse
                {
                    IDHouse = obj.IDHouse,
                    IDAddress = IDAddress1,
                });
                db.AddressHouses.Add(new AddressHouse
                {
                    IDHouse = obj.IDHouse,
                    IDAddress = IDAddress2,
                });
                db.AddressHouses.Add(new AddressHouse
                {
                    IDHouse = obj.IDHouse,
                    IDAddress = IDAddress3,
                });
            }
            else
            {
                db.Entry(obj).State = System.Data.Entity.EntityState.Modified;
                InfoHouse.ToList().ForEach(q =>
                {
                    if (q.IDInfoHouse > 0)
                    {
                        if (db.InfoHouses.FirstOrDefault(a => a.IDInfoHouse == q.IDInfoHouse) is InfoHouse ob)
                        {
                            if (q.Value == null)
                                db.InfoHouses.Remove(ob);
                            else
                            {
                                ob.Value = q.Value;
                            }
                        }
                    }
                    else if (q.Value != null && q.IDInfoHouse == 0)
                    {
                        db.InfoHouses.Add(q);
                    }
                });
            }

            foreach (var item in this.RequestAndSaveImage(true))
            {
                db.ImageHouses.Add(new ImageHouse
                {
                    IDHouse = obj.IDHouse,
                    Link = item,
                    IDImageHouse = 0,
                    Name = "View",
                    Rank = 0
                });
            }

            db.SaveChanges();
            return RedirectToAction("Index");
        }

        private House _fillInfo(House item)
        {
            if (item != null)
            {
                item.xImage = item.ImageHouses.FirstOrDefault(q => q.IDHouse == item.IDHouse && q.Rank == 0);
                item.xAddress1 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 1)?.Address;
                item.xAddress2 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 2)?.Address;
                item.xAddress3 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 3)?.Address;
            }
            return item;
        }

        public JsonResult State(int IDHouse, byte newState)
        {
            db.Houses.Find(IDHouse).State = newState;
            return Json(db.SaveChanges());
        }
    }
}

WebsiteMVC/Controllers/HouseController.cs
using Bootstrap.Pagination;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebsiteMVC.Models;

namespace WebsiteMVC.Controllers
{
    public class HouseController : BaseController
    {
        public HOUSEEntities1 db = new HOUSEEntities1();

        #region Index
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Load top 6 nhà Hot
        /// </summary>
        /// <returns></returns>
        public ActionResult TopHouse(bool? IsBan)
        {
            var lst = db.Houses.Where(q => q.State != MState.DELETE).Take(3 * 1).ToList();
            foreach (var item in lst)
            {
                item.xImage = item.ImageHouses.FirstOrDefault(q => q.IDHouse == item.IDHouse && q.Rank == 0);
                item.xAddress1 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 1)?.Address;
                item.xAddress2 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 2)?.Address;
                item.xAddress3 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 3)?.Address;
            }

            ViewBag.IsBan = IsBan;
            return View(lst);
        }
        #endregion

        #region Detail
        /// <summary>
        /// Chi tiết nhà
        /// </summary>
        /// <param name="IDHouse"></param>
        /// <returns></returns>
        public ActionResult Detail(int IDHouse)
        {
            var item = db.Houses.Find(IDHouse);
            if (item != null)
            {
                item.Views++;
                db.SaveChanges();
            }
            item.xImage = item.ImageHouses.FirstOrDefault(q => q.IDHouse == item.IDHouse && q.Rank == 0);
            item.xAddress1 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 1)?.Address;
            item.xAddress2 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 2)?.Address;
            item.xAddress3 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 3)?.Address;
            return View(item);
        }

        public ActionResult InfoHouse(int id)
        {
            var obj = db.Houses.Find(id);
            return View(obj.InfoHouses.ToList());
        }

        public ActionResult ImageHouse(int id)
        {
            return View(db.Houses.Find(id).ImageHouses.ToList());
        }

        public ActionResult More(int? IDHouse, bool? IsCungDuAn)
        {
            var house = _fillInfo(db.Houses.Find(IDHouse));

            var lst = new List<House>();
            if (IsCungDuAn.HasValue)
            {
                lst = db.Houses.Where(q => q.IDDuAn == house.IDDuAn && q.IDHouse != IDHouse).Take(10).ToList();
            }
            else
            {
                lst = db.Houses.Where(q => q.AddressHouses.Any(a => a.IDAddress == house.xAddress1.IDAddress) && q.AddressHouses.Any(a => a.IDAddress == house.xAddress2.IDAddress)).Take(3).ToList();
            }

            lst.ForEach((item) => { _fillInfo(item); });

            if (IsCungDuAn.HasValue)
            {
                return View("CungDuAn", lst);
            }
            return View(lst);
        }

        private House _fillInfo(House item)
        {
            item.xImage = item.ImageHouses.FirstOrDefault(q => q.IDHouse == item.IDHouse && q.Rank == 0);
            item.xAddress1 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 1)?.Address;
            item.xAddress2 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 2)?.Address;
            item.xAddress3 = @item.AddressHouses.FirstOrDefault(q => q.Address.Rank == 3)?.Address;
            return item;
        }

        #endregion

        #region Search

        const int LENGTH = 10;

        public ActionResult Search(Search search)
        {
            var lst = db.Houses.Where(q => q.State != MState.DELETE);
/*
            if (search.PriceFrom.HasValue)
            {
                lst = lst.Where(q => q.Price > search.PriceFrom);
            }

            if (search.PriceTo.HasValue)
            {
                lst = lst.Where(q => q.Price < search.PriceTo);
            }
*/
            if (string.IsNullOrWhiteSpace(search.NameOrCode) == false)
            {
                lst = lst.Where(q => q.Code.ToLower().Contains(search.NameOrCode.ToLower()) || q.Name.ToLower().Contains(search.NameOrCode.ToLower()));
            }
            if (search.BedRoom > 0)
            {
                if (search.BedRoom == 5)
                {
                    lst = lst.Where(q => q.BedRoom >= search.BedRoom);
                }
                else
                {
                    lst = lst.Where(q => q.BedRoom == search.BedRoom);
                }
            }

            if (search.CheckArea == true)
            {
                lst = lst.Where(q => q.Area >= search.AreaFrom && q.Area <= search.AreaTo);
            }

            if (string.IsNullOrWhiteSpace(search.Type) == false)
            {
                lst = lst.Where(q => q.Type == search.Type);
            }

            var data = lst.ToList();
            data.ForEach(item => _fillInfo(item));

            var pagination = new Pagination(data.Count, search.Page ?? 1, 10, LENGTH);
            ViewBag.pagination = pagination;

            ViewBag.AreaFrom = search.AreaFrom;
            ViewBag.AreaTo = search.AreaTo;
            ViewBag.BedRoom = search.BedRoom;
            ViewBag.CheckArea = search.CheckArea;
            ViewBag.NameOrCode = search.NameOrCode;
            ViewBag.Page = search.Page;
            ViewBag.PriceFrom = search.PriceFrom;
            ViewBag.PriceTo = search.PriceTo;
            ViewBag.Type = search.Type;
            ViewBag.search = search;

            return View(data.Skip(pagination.Skipped).Take(LENGTH));
        }

        public ActionResult ListPage(Search search)
        {
            var lst = db.Houses.Where(q => q.State != MState.DELETE);
            if (string.IsNullOrWhiteSpace(search.NameOrCode) == false)
            {
                lst = lst.Where(q => q.Code.ToLower().Contains(search.NameOrCode.ToLower()) || q.Name.ToLower().Contains(search.NameOrCode.ToLower()));
            }
            if (search.BedRoom > 0)
            {
                if (search.BedRoom == 5)
                {
                    lst = lst.Where(q => q.BedRoom >= search.BedRoom);
                }
                else
                {
                    lst = lst.Where(q => q.BedRoom == search.BedRoom);
                }
            }

            if (search.CheckArea == true)
            {
                lst = lst.Where(q => q.Area >= search.AreaFrom && q.Area <= search.AreaTo);
            }

            if (string.IsNullOrWhiteSpace(search.Type) == false)
            {
                lst = lst.Where(q => q.Type == search.Type);
            }

            var data = lst.ToList();
            data.ForEach(item => _fillInfo(item));

            var pagination = new Pagination(data.Count, search.Page ?? 1, 10, LENGTH);
            ViewBag.pagination = pagination;

            ViewBag.AreaFrom = search.AreaFrom;
            ViewBag.AreaTo = search.AreaTo;
            ViewBag.BedRoom = search.BedRoom;
            ViewBag.CheckArea = search.CheckArea;
            ViewBag.NameOrCode = search.NameOrCode;
            ViewBag.Page = search.Page;
            ViewBag.PriceFrom = search.PriceFrom;
            ViewBag.PriceTo = search.PriceTo;
            ViewBag.Type = search.Type;
            ViewBag.search = search;

            return View(data.Skip(pagination.Skipped).Take(LENGTH));
        }
        #endregion

        #region GT
        public ActionResult GT()
        {
            return View();
        }
        #endregion
    }

    public class BaseController : Controller
    {
        public HOUSEEntities1 db = new HOUSEEntities1();
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebsiteMVC/Areas/AdminCP/Views/House/Edit.cshtml
@model WebsiteMVC.Models.House

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/AdminCP/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading"><i class="fa fa-pencil"></i> @ViewBag.Title</div>
    <div class="panel-body">

        @using (Html.BeginForm("Edit", "House", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.IDHouse)
                @Html.HiddenFor(model => model.State)

                <h2>Thông tin chính</h2>

                <div class="form-group">
                    @Html.LabelFor(model => model.Code, "Mã", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon1">H</span>
                            @Html.TextBoxFor(model => model.Code, new { @class = "form-control", required = "true" })
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IDTaiKhoan, "Chuyên viên phụ trách", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(q => q.IDTaiKhoan, ViewBag.IDTaiKhoans as SelectList, "Vui lòng chọn", htmlAttributes: new { @class = "form-control", required = "true" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, "Tên nhà", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control", required = "true" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Sumary, "Mô tả ngắn", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Sumary, new { @class = "form-control", required = "true" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IDDuAn, "Thuộc dự án", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(q => q.IDDuAn, ViewBag.IDDuAns as SelectList, "Chọn dự án", htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Views, "Số lượt xem", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Views, new { @class = "form-control", required = "true", type = "number" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.State, "Cho thuê/Bán", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <label>@Html.RadioButtonFor(q => q.State, "THUE") Cho thuê</label>
                        <label>@Html.RadioButtonFor(q => q.State, "BAN") Bán</label>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IDMap, "Vị trí GG Map", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.IDMap, new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BedRoom, "Số phòng ngủ", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.BedRoom, new { @class = "form-control", required = "true", type = "number" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Area, "Diện tích", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-3">
                        <div class="input-group">
                            @Html.TextBoxFor(model => model.Area, new { @class = "form-control", required = "true", type = "number" })
                            <span class="input-group-addon" id="basic-addon1">m2</span>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Price, "Giá bán/cho thuê", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Price, new { @class = "form-control", required = "true" })
                    </div>
                </div>

                <hr />
                <div class="form-group">
                    @Html.Label("Địa chỉ nhà", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="col-md-3">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">Xã</span>
                                @Html.DropDownList("IDAddress3", ViewBag.xAddress3s as SelectList, "Vui lòng chọn", htmlAttributes: new { @class = "form-control", required = "true" })
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">Huyện</span>
                                @Html.DropDownList("IDAddress2", ViewBag.xAddress2s as SelectList, "Vui lòng chọn", htmlAttributes: new { @class = "form-control", required = "true" })
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="input-group">
                                <span class="input-group-addon" id="basic-addon1">Tỉnh</span>
                                @Html.DropDownList("IDAddress1", ViewBag.xAddress1s as SelectList, "Vui lòng chọn", htmlAttributes: new { @class = "form-control", required = "true" })
                            </div>
                        </div>
                    </div>
                </div>

                <hr />
                @Html.Action("InfoHouse", new { id = Model.IDHouse })
                <hr />
                <h2>Hình ảnh</h2>
                <p>Upload ảnh mới: <input type="file" name="Image" value="" multiple /></p>
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <td>Hình ảnh</td>
                            <td>Mô tả ngắn</td>
                            <td>Thứ tự</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.ImageHouses.Count; i++)
                        {
                            var ImageHouses = Model.ImageHouses.ToList();
                            @Html.HiddenFor(q => ImageHouses[i].Link)
                            @Html.HiddenFor(q => ImageHouses[i].IDImageHouse)
                            @Html.HiddenFor(q => ImageHouses[i].IDHouse)
                            <tr>
                                <td><img src="@ImageHouses[i].Link" alt="@ImageHouses[i].Link" style="max-height: 100px" /></td>
                                <td>
                                    @Html.TextBoxFor(q => ImageHouses[i].Name)
                                </td>
                                <td>
                                    @Html.TextBoxFor(q => ImageHouses[i].Rank)
                                </td>
                                <td>
                                    <span class="btn btn-warning"><i class=" fa fa-trash-o" k></i> Xóa</span>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn green" />
                        <a href="@Url.Action("Index")" class="btn btn-default"><i class="fa fa-arrow-circle-o-left"></i> QUAY LẠI DANH SÁCH</a>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

WebsiteMVC/Areas/AdminCP/Views/House/InfoHouse.cshtml
@model List<WebsiteMVC.Models.InfoHouse>

@{
    var gr = Model.GroupBy(q => q.Key.IDCategory).OrderBy(q => q.First().Key.Category.Rank).ThenBy(q => q.First().Key.Rank);
}

@for (int i = 0; i < gr.Count(); i++)
{
    var InfoHouse = gr.ElementAt(i).ToList();
    <h2>@InfoHouse.First().Key.Category.Name</h2>
    for (int j = 0; j < InfoHouse.Count(); j++)
    {
        var ob = InfoHouse.ElementAt(j);
        <div class="form-group">
            @Html.Hidden($"InfoHouse[{i * gr.Count() + j}].IDInfoHouse",InfoHouse[j].IDInfoHouse)
            @Html.Hidden($"InfoHouse[{i * gr.Count() + j}].IDHouse",InfoHouse[j].IDHouse)
            @Html.Hidden($"InfoHouse[{i * gr.Count() + j}].IDKey",InfoHouse[j].IDKey)
            @if (ob.Key.Type == "check")
            {
                @Html.Label(" ", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <label>
                        @if (ob.Value == "true")
                        {
                            @Html.TextBox($"InfoHouse[{i * gr.Count() + j}].Value", "true", new { @class = "form-control", type = "checkbox", @Value = "true", @checked = "true" })
                        }
                        else
                        {
                            @Html.TextBox($"InfoHouse[{i * gr.Count() + j}].Value", "true", new { @class = "form-control", type = "checkbox", @Value = "true" })
                        }
                        @ob.Key.Name
                    </label>
                </div>
            }
            else
            {
                @Html.Label(ob.Key.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextArea($"InfoHouse[{i * gr.Count() + j}].Value", ob.Value, new { @class = "form-control", Rows = "2" })
                </div>
            }
        </div>
    }
}